name: 'Infrastructure Drift Healer'

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  rg:
    uses: ./.github/workflows/terraform-reusable.yml
    with:
      component: 'rg'
      operation: 'apply'
    secrets: inherit

  acr:
    needs: rg
    uses: ./.github/workflows/terraform-reusable.yml
    with:
      component: 'acr'
      operation: 'apply'
    secrets: inherit

  aks:
    needs: acr
    uses: ./.github/workflows/terraform-reusable.yml
    with:
      component: 'aks'
      operation: 'apply'
    secrets: inherit
