name: 'Terraform Security and Plan'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  rg:
    uses: ./.github/workflows/terraform-reusable.yml
    with:
      component: 'rg'
      operation: 'plan'
    secrets: inherit

  acr:
    needs: rg
    uses: ./.github/workflows/terraform-reusable.yml
    with:
      component: 'acr'
      operation: 'plan'
    secrets: inherit

  aks:
    needs: acr
    uses: ./.github/workflows/terraform-reusable.yml
    with:
      component: 'aks'
      operation: 'plan'
    secrets: inherit
